name: news_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 5.0.8+28

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.0
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.5
  dots_indicator: ^2.1.0

  firebase_auth: ^4.6.1
  firebase_core: ^2.4.1
  firebase_messaging: ^14.6.1
  firebase_storage: ^11.2.1
  flutter_web_browser: ^0.17.1
  flutter_html: ^3.0.0-beta.2
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.1
  html_unescape: ^2.0.0
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  introduction_screen: ^3.1.8
  launch_review: ^3.0.1
  line_icons: ^2.0.1
  lottie: ^2.3.2
  package_info: ^2.0.2
  path_provider: ^2.0.15
  provider: ^6.0.5
  share: ^2.0.4
  shared_preferences: ^2.1.1
  skeleton_text: ^3.0.1
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.11
  youtube_player_flutter: ^9.0.0
  rounded_loading_button: ^2.0.9
  firebase_analytics: ^10.4.1
  flutter_facebook_auth: ^5.0.11
  the_apple_sign_in: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  jiffy: ^5.0.0
  loading_indicator: ^3.1.0
  reading_time: ^2.0.0
  pod_player: ^0.1.4
  google_mobile_ads: ^3.0.0
  # facebook_audience_network: ^1.0.1
  app_settings: ^5.1.1
  csslib: 0.17.2
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  md2_tab_indicator:
    git:
      url: https://github.com/westdabestdb/md2_tab_indicator
  get: ^4.6.6
  
 
  
  timeago: ^3.6.1
  video_compress: ^3.1.2
  video_player: ^2.8.2
  velocity_x: ^4.1.2
  better_player: ^0.0.83
  flutter_bloc: ^8.1.4
  permission_handler: ^11.0.1
  country_picker: ^2.0.23
  pinput: ^4.0.0
  country_state_city_picker: ^1.2.8
  webview_flutter: ^4.5.0
  firebase_database: ^10.4.0
  
  telephony: ^0.2.0
  connectivity_plus: ^5.0.2
  font_awesome_flutter: ^10.7.0
 
  easy_localization: ^3.0.5
  flutter_multi_select_items: ^0.4.2
  flutter_multiselect: ^1.0.0
  multi_select_flutter: ^4.1.3
  multiselect_formfield: ^0.1.7
  visibility_detector: ^0.3.3
  flutter_localizations:
    sdk: flutter
  location: ^5.0.3
  geocoding: ^3.0.0
  
  
  
  
 
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.1.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"



# The following section is specific to Flutter.
flutter:
  

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation_files/
    - assets/translations/

  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500

    - family: Manrope
      fonts:
        # - asset: assets/fonts/Manrope-Light.ttf
        #   weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900
