// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbiyEa1i302wwo-bahapghdhXIooHPygM',
    appId: '1:259474020635:web:ccaaff69f102fede1a5bbe',
    messagingSenderId: '259474020635',
    projectId: 'apna-shahar-12b5a',
    authDomain: 'apna-shahar-12b5a.firebaseapp.com',
    storageBucket: 'apna-shahar-12b5a.appspot.com',
    measurementId: 'G-4R31MS2YX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeq42Yd29lceKddqDFzC8TTdEAhNhU4iI',
    appId: '1:259474020635:android:4bf7c8868363414c1a5bbe',
    messagingSenderId: '259474020635',
    projectId: 'apna-shahar-12b5a',
    storageBucket: 'apna-shahar-12b5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArbDuilcxEWd4d7blKox9pImb0VIsdkck',
    appId: '1:259474020635:ios:725516267f4d90e01a5bbe',
    messagingSenderId: '259474020635',
    projectId: 'apna-shahar-12b5a',
    storageBucket: 'apna-shahar-12b5a.appspot.com',
    iosBundleId: 'mrblab.newshourapp',
  );
}
